# Generated by Django 5.0.6 on 2024-05-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='files',
            field=models.FileField(default=1, upload_to='./xx/'),
            preserve_default=False,
        ),
    ]
